# import User from "../../users/type-defs/User.gql"

scalar Upload

type AuthData {
  token: String!
  user: User!
}

type Query {
  login(email: String!, password: String!): AuthData!
  logout: String!
}

input UserInput {
  email: String!
  username: String!
  password: String!
  avatar: String
}

type Mutation {
  register(input: UserInput!): User!
}
