# import User from "../../users/type-defs/User.gql"

type Recipe {
  _id: ID!
  user: User!
  name: String!
  ingredients: [Ingredient]!
  description: String
  instructions: String
  picturePath: String
  cookingTime: Int!
  difficulty: String!
  likesCount: Int
  likedByUser: Boolean
  comments: [Comment]
  createdAt: String!
}

type Ingredient {
  name: String!
  amount: String
}

type Comment {
  user: User!
  text: String!
  createdAt: String!
}

input CommentInput {
  id: ID!
  text: String!
}

input RecipeInput {
  name: String!
  ingredients: [IngredientInput]!
  description: String
  instructions: String
  picturePath: String
  cookingTime: Int!
  difficulty: String!
}

input IngredientInput {
  name: String!
  amount: String
}

type Query {
  getAllRecipes: [Recipe]!
  getRecipe(id: ID!): Recipe
  getRecipesByAuthor(userId: ID!): [Recipe]!
  getRecipesByIngredients(ingredients: [String], matchAll: Boolean): [Recipe]!
  getComments(id: ID!): [Comment]!
}

type Mutation {
  createRecipe(input: RecipeInput!): Recipe
  updateRecipe(id: ID!, input: RecipeInput!): Recipe!
  deleteRecipe(id: ID!): String
  likeRecipe(id: ID!): Recipe!
  commentRecipe(input: CommentInput!): [Comment]!
}
